hyperledger/sawtooth-sabre

docs/Dockerfile
=> Add pkg-config to docs/Dockerfile

cli/src/main.rs
Before if you tried to use the cli without --wait
it would panic. Now it defaults to 0 if wait
is not provided and returns a UserError if wait is
not an integer.
=> Make --wait optional in sabre cli

cli/src/main.rs, example/intkey_multiply/processor/src/handler.rs, integration/tests/test_sabre.rs, sdk/src/externs.rs, sdk/src/lib.rs, tp/src/handler.rs, tp/src/wasm_executor/wasm_externals.rs
Also updates the cli to accept multiple inputs and outputs.
Adds delete_state to the sabre sdk.
This should not be merged until https://github.com/hyperledger/sawtooth-core/pull/1722 is merged into sawtooth core.
=> Update Sabre to work with the new get_state/set_state

Jenkinsfile
Tags are required to get the dev version number and JJB multibranch
fetches without tags.
=> Fetch git tags in Jenkinsfile

Jenkinsfile, docs/docker-compose.yaml
Jenkins runs each sh command in a separate sub-shell, this caused the
wrong docker-compose file to run during the "Build documentation" stage.
=> Fixups to the build system

cli/build.rs, tp/build.rs
Protobuf updated and removed Default::default() and
instead we need to use Customize::default()
Note sabre will not build until sawtooth core is updated.
=> Update build.rs files to use Customize::default()

docs/source/sabre_transaction_family.rst
Corrected the Sabre Transaction Family documentation:
sawtooth.swa.administrators is an input (not output).
Signed-off-by: Anne Chenette <chenette@bitwise.io>
=> Fix DeleteContractRegistryAction inputs/outputs

docs/source/application_developer_guide.rst, docs/source/sabre_transaction_family.rst
Rewrite to expand, clarify, update, edit, and format information. Changes include:
- Rewrite throughout to clarify information, make consistent with procedures in
the Sawtooth core docs, and format as a procedure
- Add introduction and prerequisites sections
- Summarize what the Docker Compose files do (describe containers, key generation,
Sawtooth administrator setting, and volume setup/key sharing between containers)
- Consistently show which container is used for each step
- Clarify that "sabre upload" uploads a contract definition file (not a
contract) and that "sabre ns" creates a namespace registry (not a namespace)
- Update the example contract definition file, with explanations of the Sabre
and Pike namespaces (in source but not shown in the previous doc)
- Delete hard-coded, …
=> Update Running a Sabre Smart Contract doc

Jenkinsfile, docker-compose-installed.yaml, docs/source/application_developer_guide.rst, docs/source/sabre_cli.rst, docs/source/sabre_transaction_family.rst, example/intkey_multiply/processor/src/handler.rs, tp/src/handler.rs
This PR updates the docker-compose-installed.yaml file to be able to run the tutorial of the documentation in `installed` mode. It makes it closer to the non-installed docker-compose.yaml file. The PR also includes separate commits for some minor documentation revisions and typos in comments or error message in rust files.
=> Run tutorial in installed mode and docs updates

Jenkinsfile
This variable prevents naming collisions in containers created by
docker-compose. This variable was missing from the Jenkinsfile rewrite.
=> add COMPOSE_PROJECT_NAME to Jenkinsfile

docker-compose.yaml, docs/docker-compose.yaml, integration/sabre_test.yaml
This will fix an issue with colliding images when
running the build in Jenkins.
=> Add Missing Isolation ID to docker compose files

docker-compose.yaml, docs/docker-compose.yaml, integration/sabre_test.yaml
This will fix an issue with colliding images when
running the build in Jenkins.
=> BACKPORT: Add Missing Isolation ID to docker compose files

cli/Cargo.toml, example/intkey_multiply/cli/Cargo.toml, example/intkey_multiply/processor/Cargo.toml, integration/Cargo.toml, sdk/Cargo.toml, tp/Cargo.toml
Sabre is going to be updated to work with the
newer version of the Sawtooth Rust SDK. As such
the version needs to be increased because it will
no longer be compatible with 0.1 version of Sabre.
=> Increase Sabre version to 0.2

tp/Cargo.toml, tp/src/handler.rs, tp/src/lib.rs, tp/src/main.rs
Split the transaction processor and handler into a binary and library outputs.  This enables the use of the sabre transaction processor from within other embedded contexts (for example, using [Transact](https://github.com/bitwiseio/transact))
=> Split Sabre TP into a library and a binary

contracts/sawtooth-pike/tp/Cargo.toml, docs/source/application_developer_guide.rst, example/intkey_multiply/processor/Cargo.toml
This will allow sabre smart contracts to be compiled on more
platforms when not compiling into wasm.
Add the wasm32 target rustup target add wasm32-unknown-unknown --toolchain nightly and run both cargo build and cargo +nightly build --target wasm32-unknown-unknown (in the respective directories). Both should pass.
=> Replace unix with not wasm32 in platform-specific dependencies

cli/src/transaction.rs, docs/source/index.rst, docs/source/version_compatibility.rst, tp/src/handler.rs
Updates the version of the Sabre family version to
0.2. This will allow someone to run both the 0.0 and
0.2 version of the Sabre TP on the same network.
=> Update Sabre family version to 0.2

docs/source/application_developer_guide.rst, example/intkey_multiply/processor/Cargo.toml, example/intkey_multiply/processor/src/handler.rs, example/intkey_multiply/processor/src/main.rs, sdk/src/lib.rs, sdk/src/log.rs
Logging does not currently compile into wasm. With these
macros a developer can write a log statement in a smart contract
that will be run normally if compiled into a transaction processor
and ignored in wasm code.
Before it was required to include the following above the log
statement:
`#[cfg(not(target_arch = "wasm32"))]`
=> Add no-op logging macros to the Sabre SDK

docs/source/application_developer_guide.rst, example/intkey_multiply/processor/src/handler.rs, sdk/src/externs.rs, sdk/src/lib.rs, sdk/src/log.rs, tp/Cargo.toml, tp/src/main.rs, tp/src/wasm_executor/wasm_externals.rs
The sabre sdk now has logging macros, where if the log level
is currently supported will format the log string, write the
string to memory and call the extern function to log the message
in the Sabre transaction processor.
The log level set on the Sabre TP will also be enforced on the
smart contracts.
=>  Add logging to Sabre SDK and wasm externals

cli/src/error.rs, contracts/sawtooth-pike/cli/src/error.rs, example/intkey_multiply/cli/src/error.rs, example/intkey_multiply/processor/src/handler.rs
Fix following nightly warning:
trait objects without an explicit `dyn` are deprecated
=> Add dyn to trait objects

cli/src/error.rs, integration/tests/test_sabre.rs, sdk/src/protocol/payload.rs, sdk/src/protocol/pike/state.rs, sdk/src/protocol/state.rs, sdk/src/protos.rs
This removes the deprecated use of description and cause.
=> Update CliError to use source instead of description and cause

cli/Dockerfile-installed-bionic, cli/Dockerfile-installed-xenial, contracts/sawtooth-pike/api/Dockerfile-installed-bionic, contracts/sawtooth-pike/api/Dockerfile-installed-xenial, contracts/sawtooth-pike/cli/Dockerfile-installed-bionic, contracts/sawtooth-pike/cli/Dockerfile-installed-xenial, contracts/sawtooth-pike/state_delta_export/Dockerfile-installed-bionic, contracts/sawtooth-pike/state_delta_export/Dockerfile-installed-xenial, contracts/sawtooth-pike/tp/Dockerfile-installed-bionic, contracts/sawtooth-pike/tp/Dockerfile-installed-xenial, tp/Dockerfile-installed-bionic, tp/Dockerfile-installed-xenial
The behavior of cargo-deb was changed to generate version numbers with
tildes instead of dashes. This is causing newly built packages to sort
below older releases.
https://github.com/mmstick/cargo-deb/pull/102
=> Fix versioning of packaged Rust components

cli/src/transaction.rs, sdk/src/protocol/mod.rs, tp/src/addressing.rs, tp/src/handler.rs, tp/src/lib.rs, tp/src/state.rs
Exposes the address of the admins setting in the SDK; this is necessary
because applications that use Sabre will need to ensure that the setting
is properly set when Sabre is started.
=> Expose the address of the admins setting

cli/src/main.rs, cli/src/upload.rs
Add a --wasm command line argument to the sabre upload command. This
argument allows a user to specify a path to the compiled smart
contract. The value will fall back to the one specified in the manifest
file if not provided. This is useful when adding a smart contract from
a SCAR file.
Signed-off-by: Davey Newhall <newhall@bitwise.io>
=> Add sabre contract upload wasm flag

docs/source/application_developer_guide.rst
Adds docs directory and `getting_started.md` which outlines how to
initialize an AssemblyScript project and how to compile AssemblyScript
to sabre compatable WebAssembly.
Signed-off-by: Ryan Banks <rbanks@bitwise.io>
=> Add getting started docs

sdks/rust/Cargo.toml, sdks/rust/src/protocol/mod.rs, sdks/rust/src/protocol/payload.rs
Add the `into_transaction_builder` method to the `SabrePayloadBuilder`
to support converting directly from a Sabre payload builder into
Transact's transaction builder.
=> SabrePayloadBuilder into TransactionBuilder

RELEASE_NOTES.md, docs/source/version_compatibility.rst
This is required due to a breaking change in 64a29d3.
=> Increment version to v0.5.0

MAINTAINERS.md
=> Add headers to retired maintainers table

example/intkey_multiply/processor/src/handler.rs, sdks/rust/src/externs.rs, sdks/rust/src/lib.rs, tp/src/wasm_executor/wasm_externals.rs
1. Add a new method to the TransactionContext to match that of sawtooth-sdk's TransactionContext for the add_event().
2. Implement TransactionContext method for the Wasm
3. Expose add_event method from the WasmExecutor.
=> Add event capability to the Sabre SDK

sdks/rust/Cargo.toml, sdks/rust/build.rs
protoc-rust::run is deprecated in 2.14. This commit updates
the build.rs files to use protoc-rust::Codegen instead.
The version requirement for protoc-rust has also been raised
from 2 to 2.14.
=> Update protoc-rust to version 2.14

example/intkey_multiply/intkey_multiply.yaml, example/intkey_multiply/processor/packaging/scar/manifest.yaml, example/intkey_multiply/processor/src/handler.rs, integration/tests/test_sabre.rs, tp/src/payload.rs
Enforces the naming requirement to not include a '_' and also
verifies that the contract version is a valid semver string.
=> Enforce contract naming requirement

sdks/rust/src/protocol/pike/state.rs, tp/src/state.rs
=> Remove redundant clones to fix Rust 1.44.0 clippy errors

tp/src/handler.rs
A transaction to create contract registry and namespace registry
or delete one will be invalidated if the signer is not an admin.
Admin and owner keys are set in the state address locations,
these are read during the time of create or delete.
However, there can be error because these values are never set.
This shall be differentiated against having the values set and
invalid signer performing the action.
Signed-off-by: S m, Aruna <aruna.mohan@walmartlabs.com>
=> Differentiate InvalidTransaction reason due to admin

cli/src/key.rs, example/intkey_multiply/cli/src/key.rs
=> Replace Result.and_then(|x| Ok(y)) with map(|x| y) in load_signing_key

cli/Cargo.toml, cli/src/error.rs, cli/src/key.rs, cli/src/main.rs, cli/src/upload.rs, sdks/rust/Cargo.toml, sdks/rust/src/protocol/payload.rs, tp/Cargo.toml, tp/src/main.rs
Requires pulling in cylinder for signing.
Also updates simple_logger usage to remove deprecation warnings.
=> Update Sabre for new Transact Release

RELEASE_NOTES.md, docs/source/version_compatibility.rst, sdks/rust/src/protocol/mod.rs
Also adds version compatibility and update SABRE_PROTOCOL_VERSION
=> Add release notes for Sabre 0.6.0

sdks/rust/src/externs.rs
attribute no_mangle should be applied to a function or static
this was previously accepted by the compiler but is being
phased out; it will become a hard error in a future release
Since, no_mangle was on extern functions, it should not be
required.
=> Remove no_mangle from sabre externs

sdks/rust/src/protocol/mod.rs, tp/src/handler.rs
The family version about the protocol of the smart contracts and
not about the version of Sabre as a whole. Setting the family
version to 1 will help remove this confusion.
0.5 and 0.6 have also been included in the family version list
so that sabre can support older client versions that are
still compatible.
=> Update the sabre family version to 1

sdks/rust/src/lib.rs
The ptr_to_vec to function was not properly checking
the return type of externs::get_ptr_len, which returns
a -1 if there is an error finding the ptr.
This issues was caught by the 1.50 clippy updates
clippy::unnecessary_wraps.
=> Properly handle error returned from externs::get_ptr_len

tp/src/admin/allow_all.rs, tp/src/admin/mod.rs, tp/src/admin/settings.rs, tp/src/handler.rs, tp/src/main.rs
The AdminPermission trait will be used to decouple the Sabre Transaction Handler
from Sawtooth Settings when checking  if a signer is an
admin.
Two implementation are provided. One to still check Settings
and one no-op implementation that always returns true.
When starting up the transaction processor provide the flag `--admin-no-op` to treat all signers as admins.
=> Break out checking if a signer is an admin into trait

cli/src/key.rs
The return type was needlessly wrapped in an Ok()
with a question mark to return if error. Instead
we can just return the value returned from
PrivateKey::new_from_hex.
This was caught by a clippy error in Rust 1.51.0
=> Fix question mark operator is useless here clippy error

.gitignore, cli/src/key.rs, contracts/sawtooth-pike/cli/Cargo.toml, contracts/sawtooth-pike/cli/src/key.rs, contracts/sawtooth-pike/cli/src/main.rs, example/intkey_multiply/cli/src/key.rs
1. Add support for keyfile (relative/absolute) path read from the CLI.
2. Update deprecated `env` with `dirs`, to get the user's home directory
3. Add IDE files in git ignore list.
=> Support custom keyfile in Sabre CLIs

contracts/sawtooth-pike/api/Cargo.toml, contracts/sawtooth-pike/cli/Cargo.toml, contracts/sawtooth-pike/state_delta_export/Cargo.toml, contracts/sawtooth-pike/tp/Cargo.toml, docs/source/application_developer_guide.rst, example/intkey_multiply/cli/Cargo.toml, example/intkey_multiply/processor/Cargo.toml
Examples were still pulling in the sawtooth-sdk from github.
They should instead be using the published crate.
This will fix lint that was caused when the rust-sdk HEAD branch
was switched to main instead of master.
=> Update all sawtooth-sdk dep to use the crate used by the tp

cli/Cargo.toml, cli/src/error.rs, cli/src/main.rs, cli/src/state.rs
The following command (with output) have been added to the sabre CLI
```
sabre contract list -h
sabre-contract-list 
List all registered Sabre smart contracts
USAGE:
sabre contract list [OPTIONS]
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
OPTIONS:
-f, --format <format>    Format to display list of smart contracts in [default: human]  [possible values: human,
csv]
-U, --url <url>          URL to the Sawtooth REST API
```
```
sabre contract list
NAME            VERSIONS OWNERS                                                             
intkey_multiply 1.0      03e0c781880ec8632ed5eb49f5613c69f6bfd67d76a2919efca1c58260fd313424 
1cf126                   test  
```
```
sabre contract show  -h
sabre-contract-show 
Show details about a registered …
```
=> Add show/list subcommands to the sabre CLI 

tp/Cargo.toml
Update the version of the wasmi library from 0.4 to 0.9 to minimize memory footprint. Changes between versions 0.4 and 0.9 of wasmi fixed an issue where unnecessarily large amounts of memory were being allocated.
=> Update wasmi version

tp/Cargo.toml
Update the version of the wasmi library from 0.4 to 0.9 to minimize
memory footprint.
=> 0-7 Backport of wasmi dependency version update

cli/Dockerfile-installed-bionic, cli/Dockerfile-installed-xenial, contracts/sawtooth-pike/api/Dockerfile-installed-bionic, contracts/sawtooth-pike/api/Dockerfile-installed-xenial, contracts/sawtooth-pike/cli/Dockerfile-installed-bionic, contracts/sawtooth-pike/cli/Dockerfile-installed-xenial, contracts/sawtooth-pike/state_delta_export/Dockerfile-installed-bionic, contracts/sawtooth-pike/state_delta_export/Dockerfile-installed-xenial, contracts/sawtooth-pike/tp/Dockerfile-installed-bionic, contracts/sawtooth-pike/tp/Dockerfile-installed-xenial, tp/Dockerfile-installed-bionic, tp/Dockerfile-installed-xenial
Switching from "-i" to "--unpack" gets rid of the caught missing
dependency errors while installing built .deb packages.
Displaying these errors, though caught, could be confusing to new
users of the project.
=> Remove known errors during .deb package install

cli/Cargo.toml, sdks/rust/Cargo.toml, sdks/rust/src/protocol/payload.rs
Includes changing HashMethod::SHA512 to HashMethod::Sha512.
Transact changed HashMethod enum to follow standard linting practices.
=> Update Transact dependency to 0.4

tp/src/admin/mod.rs
Newer versions of scabbard require that the trait be Send.
Signed-off-by: Caleb Hill <hill@bitwise.io>
=> Make AdminPermission trait Send

tp/Cargo.toml, tp/src/main.rs
This change updates simple logger to be configured with UTC timestamps. Local timestamps require a compiler flag, unsound_local_offset, which is required by a transient dependency.  The time crate (the transient
dependency in question) describes this flag as untested, and it fails in certain environments, such as CI.
See https://time-rs.github.io/internal-api/time/index.html#feature-flags for more information
=> Switch simple logger to use UTC timestamps

justfile, tp/Cargo.toml, tp/src/main.rs
Starting with version 0.11.0, just ignores .env files by default. This
breaks some recipes because we read docker environment variables from
the .env file.
=> BACKPORT 0-7: Set dotenv-load to true in justfile

justfile, tp/Cargo.toml, tp/src/main.rs
Starting with version 0.11.0, just ignores .env files by default. This
breaks some recipes because we read docker environment variables from
the .env file.
=> BACKPORT 0-5: Set dotenv-load to true in justfile

cli/src/main.rs
Addresses clippy lints introduced with Rust 1.62.
Signed-off-by: Chris Eckhardt <eckhardt@bitwise.io>
=> Fix linting from 1.62

CODEOWNERS, MAINTAINERS.md
They have previously indicated they wished to be retired.
=> Retire Logan from maintainers and codeowners
