- docs/source/conf.py
> Update sphinx theme to match the other docs.

- cli/Cargo.toml
- cli/build.rs
- tp/Cargo.toml
- tp/Dockerfile
- tp/build.rs
> Make sabre compatible with protoc 1.6

- cli/Cargo.toml
- tp/Cargo.toml
> Update protobuf to version 2

- .env
- .gitignore
- Jenkinsfile
- bin/whitelist
- ci/sawtooth-sabre-cli
- ci/sawtooth-sabre-tp
- cli/Dockerfile-installed
- docker-compose-installed.yaml
- tp/Cargo.toml
- tp/Dockerfile-installed
- tp/packaging/systemd/sawtooth-sabre
- tp/packaging/systemd/sawtooth-sabre.service
- tp/packaging/ubuntu/postinst
Adds files for building and packaging the sabre tp and cli.
> Sabre packaging

- .gitignore
- cli/Cargo.toml
- docs/source/application_developer_guide.rst
- example/intkey_multiply/processor/src/handler.rs
- integration/Cargo.toml
- sdk/Cargo.toml
- sdk/src/lib.rs
- tp/src/handler.rs
- tp/src/wasm_executor/wasm_module.rs
Also updates the version numbers to 0.1.1 for dockerhub publishing.
> Add get_signature to Sabre TpProcessRequest

- sdk/src/lib.rs
- tp/src/wasm_executor/wasm_externals.rs
> Fix bug where set error was not being handled

- tp/Cargo.toml
https://git.cglcloud.com/DigitalSupplyChain/sawtooth-sabre/pull/32
Signed-off-by: Ryan Banks <rbanks@bitwise.io>
> Update wasmi dependency

- cli/src/contract_registry.rs
- cli/src/main.rs
- cli/src/transaction.rs
- docs/bin/generate_cli_output
- docs/source/application_developer_guide.rst
- docs/source/sabre_cli.rst
- docs/source/sabre_transaction_family.rst
- integration/tests/test_sabre.rs
- tp/src/handler.rs
This PR address several comments left by @dcmiddle during the Sabre RFC process.
>  Contract Registries can only be created by admins

- ci/sawtooth-sabre-cli
- ci/sawtooth-sabre-tp
- cli/Dockerfile
- contracts/sawtooth-pike/cli/Dockerfile
- contracts/sawtooth-pike/cli/Dockerfile-installed
- example/intkey_multiply/cli/Dockerfile
> Update dockerfiles to use bumper/stable apt repo

- docs/source/application_developer_guide.rst
Signed-off-by: Anne Chenette <chenette@bitwise.io>
> Fix Sabre typo

- docs/source/application_developer_guide.rst
Change for "Converting a Transaction Processor to a Smart Contract".
Signed-off-by: Anne Chenette <chenette@bitwise.io>
> Add macro_use to main.rs example in App Dev Guide

- docs/Dockerfile
> Unpin Sphinx version

- docs/source/index.rst
- docs/source/sabre_transaction_family.rst
1) Minor typo fix in Sabre Transaction Family
2) Sphinx warnings fix
Signed-off-by: Rajeev Ranjan <rajeev2.ranjan@intel.com>
> Documentation typo fix

- Jenkinsfile
> Properly shutdown integration/sabre_test.yaml in Jenkinsfile

- Jenkinsfile
> Backport: Properly shutdown integration/sabre_test.yaml in Jenkinsfile

- docs/source/application_developer_guide.rst
> Fix some doc formatting issues

- cli/Dockerfile-installed-bionic
- tp/Dockerfile-installed-bionic
> Fix improperly versioned packages

- cli/Cargo.toml
- cli/src/contract_registry.rs
- cli/src/execute.rs
- cli/src/key.rs
- cli/src/main.rs
- cli/src/namespace.rs
- cli/src/smart_permission.rs
- cli/src/submit.rs
- cli/src/transaction.rs
- cli/src/upload.rs
- example/intkey_multiply/cli/Cargo.toml
- example/intkey_multiply/cli/src/key.rs
- example/intkey_multiply/cli/src/main.rs
- example/intkey_multiply/cli/src/multiply.rs
- example/intkey_multiply/cli/src/submit.rs
- example/intkey_multiply/cli/src/transaction.rs
- example/intkey_multiply/processor/Cargo.toml
- example/intkey_multiply/processor/src/handler.rs
- example/intkey_multiply/processor/src/main.rs
- integration/Cargo.toml
- integration/tests/test_sabre.rs
- sdk/Cargo.toml
- sdk/src/lib.rs
The Transaction Processor had already been updated.
This commit updates the remaining code: cli, sdk,
examples and tests.
It also updates the use statements to be in our standard
sections of external, std, and internal.
> Update all sabre code to Rust edition 2018

- contracts/sawtooth-pike/tp/Cargo.toml
- docs/source/application_developer_guide.rst
- example/intkey_multiply/processor/Cargo.toml
> Replace rust-crypto fork with rust-crypto-wasm 0.3

- ci/sawtooth-sabre-cli
- ci/sawtooth-sabre-tp
> Update ci dockerfiles to install from chime repo

- Jenkinsfile
- bin/run_lint
- cli/Cargo.toml
- cli/Dockerfile
- cli/Dockerfile-installed-bionic
- cli/Dockerfile-installed-xenial
- cli/src/key.rs
- cli/src/main.rs
- cli/src/transaction.rs
- cli/src/upload.rs
- docker/lint
- example/intkey_multiply/cli/Cargo.toml
- example/intkey_multiply/cli/Dockerfile
- example/intkey_multiply/cli/src/key.rs
- example/intkey_multiply/cli/src/main.rs
- example/intkey_multiply/cli/src/multiply.rs
- example/intkey_multiply/cli/src/transaction.rs
- example/intkey_multiply/processor/Dockerfile
- example/intkey_multiply/processor/src/handler.rs
- sdk/src/lib.rs
- tp/Dockerfile
- tp/Dockerfile-installed-bionic
- tp/Dockerfile-installed-xenial
- tp/src/addressing.rs
- tp/src/handler.rs
- tp/src/state.rs
- tp/src/wasm_executor/wasm_externals.rs
- tp/src/wasm_executor/wasm_module.rs
There are quite a few commits because it is broken up by clippy error so the change can be understood and broken up by component.
> Updates Clippy and Rust formatting issues and adds the linting to the jenkins files

- docs/source/_templates/indexcontent.html
> Add Sabre Version Compatblity to indexcontent.html

- cli/Cargo.toml
- cli/src/transaction.rs
- docs/source/version_compatibility.rst
- example/intkey_multiply/cli/Cargo.toml
- example/intkey_multiply/processor/Cargo.toml
- integration/Cargo.toml
- sdk/Cargo.toml
- tp/Cargo.toml
- tp/src/handler.rs
This PR should be merged before the next release.
> Update Sabre version to 0.4

- ci/sawtooth-sabre-tp
> Add gpg to tp Dockerfile for Docker Hub

- ci/sawtooth-publish-crates
> Add dockerfile for publishing sdk to crates

- Jenkinsfile
- docker-compose-installed.yaml
- example/intkey_multiply/processor/Dockerfile-scar
- example/intkey_multiply/processor/packaging/scar/manifest.yaml
> Package intkey_multiply as .scar file

- tp/src/wasm_executor/wasm_externals.rs
> Remove unnecessary unwrap from wasm_externals.rs

- integration/Dockerfile
> Remove rust nightly from sabre intergration dockerfile

- docs/source/application_developer_guide.rst
Signed-off-by: S m, Aruna <aruna.mohan@walmartlabs.com>
> Documentation error fixes

- example/intkey_multiply/processor/src/handler.rs
- sdk/src/lib.rs
- tp/src/addressing.rs
- tp/src/handler.rs
> Fix clippy lint from 1.40 update

- ci/sabre-publish-sdk-crates
> Fix broken path in Dockerfile for publishing sdk

- cli/src/transaction.rs
- tp/src/handler.rs
> Update family version for Sabre transactions in tp and cli

- RELEASE_NOTES.md
> Add release notes for v0.5.1

- contracts/inc-dec-key/assembly/index.ts
- sdks/assemblyscript/assembly/index.ts
This PR adds basic error handling to the AssemblyScript SDK in the form of a `Result` class.
> Add basic error handling

- cli/Dockerfile-installed-bionic
- sdks/rust/src/protocol/mod.rs
- sdks/rust/src/protocol/payload.rs
- tp/src/handler.rs
Fixes some of the addressing methods and the `into_transaction_builder` method.
> Fixes for Sabre SDK

- RELEASE_NOTES.md
> Add release notes for v0.5.2

- CODEOWNERS
- MAINTAINERS.md
> Propose Logan Seeley as a maintainer

- cli/src/error.rs
- example/intkey_multiply/cli/src/error.rs
- example/intkey_multiply/processor/src/main.rs
- sdks/rust/src/lib.rs
- tp/src/main.rs
- tp/src/wasm_executor/wasm_externals.rs
Fixes clippy errors caused by the new rust version
> Rust1.42 update fixes

- example/intkey_multiply/intkey_multiply.yaml
- example/intkey_multiply/processor/packaging/scar/manifest.yaml
- example/intkey_multiply/processor/src/handler.rs
- integration/tests/test_sabre.rs
- tp/src/payload.rs
This reverts commit 678db7867c2fb41dc7c907c967e43dc1281cb539, reversing
changes made to 82bcc583e325bad51182e9462cb9878042c69efa.
Signed-off-by: Shannyn Telander <telander@bitwise.io>
> Revert "Merge pull request #110 from Cargill/shannynalayna-validate-contract-name"

- tp/Cargo.toml
Signed-off-by: Shannyn Telander <telander@bitwise.io>
> Update Sawtooth SDK from 0.3 -> 0.4.4

- cli/Cargo.toml
- sdks/rust/Cargo.toml
> Update Rust SDK cylinder dep to 0.2

- RELEASE_NOTES.md
> Add release notes for 0.6.1

- Jenkinsfile
> Update Jenkinsfile for 0-5 branch

- example/intkey_multiply/processor/Cargo.toml
> Fix log4s version

- RELEASE_NOTES.md
> Add release notes for 0.7.1

- .env
- Jenkinsfile
- docker-compose-installed.yaml
- example/intkey_multiply/processor/Dockerfile-scar
> Properly version intkeym scar file

- .gitignore
- Jenkinsfile
- cli/src/key.rs
- contracts/sawtooth-pike/api/Cargo.toml
- contracts/sawtooth-pike/cli/Cargo.toml
- contracts/sawtooth-pike/state_delta_export/Cargo.toml
- contracts/sawtooth-pike/tp/Cargo.toml
- docs/source/application_developer_guide.rst
- example/intkey_multiply/cli/Cargo.toml
- example/intkey_multiply/processor/Cargo.toml
A few minor commits cherry-picked from main for the 0-7 branch. This includes necessary linting fixes, a fix to use the published sawtooth sdk, etc.
> Backports from main to 0-7

- RELEASE_NOTES.md
Signed-off-by: Isabel Tomb <tomb@bitwise.io>
> Add release notes for 0.7.2

- justfile
A couple fix including fixing 'just clean'.
> Fix justfile

- .github/workflows/build-docker.yaml
> Fetch tags during GHA PR docker builds

- .github/workflows/merge.yaml
This was inadvertently omitted in PR#119.
> Remove docs build from merge GHA workflow

- .github/workflows/merge.yaml
> Remove docs dependency from publish artifacts step
